version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: local_rag_qdrant
    restart: always
    ports:
      - "6333:6333" # REST API & Web Dashboard
      - "6334:6334" # gRPC Interface
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
    driver: local
